# Example of AD in slides

In [1]:
import numpy as np

In [2]:
def forward(x = np.array([1., 1.])):
    
    x[0] = x[0]**2 + x[1]

    x[1] = x[0] + x[1]**2
    
    J = x[0] + x[1]
    
    return J

In [3]:
def finite_diff_grad(x = np.array([1., 1.]), eps = 1.e-7):
    
    J = forward(x.copy())
    g = np.zeros(x.shape)
    
    for i in range(x.shape[0]):
        
        x_perturb = x.copy()
        x_perturb[i] = x_perturb[i] + eps
        J_perturb = forward(x_perturb.copy())
        
        g[i] = (J_perturb - J) / eps
    
    return g

finite_diff_grad()

array([4.00000021, 4.00000011])

In [10]:
def TLM_grad(x = np.array([1., 1.])):

    dx = np.zeros(x.shape)
    g = np.zeros(x.shape)
    x_orig = x.copy()
    
    for i in range(x.shape[0]):
        
        dx[:] = 0.0
        x = x_orig.copy()
        dx[i] = 1.0

        dx[0]  = 2*x[0]*dx[0] + dx[1]
        x[0]   = x[0]**2 + x[1]

        dx[1]  = dx[0] + 2*x[1]*dx[1]
        x[1]   = x[0] + x[1]**2

        g[i]  = dx[0] + dx[1]
        J     = x[0] + x[1]
    
    return g
    
TLM_grad()

array([4., 4.])

In [16]:
def adj_store_grad(x = np.array([1., 1.])):

    tape = []
    
    tape.append(np.copy(x))
    x[0] = x[0]**2 + x[1]


    tape.append(np.copy(x))
    x[1] = x[0] + x[1]**2

    J = x[0] + x[1]
    
    xb = np.zeros(x.shape)
    Jb = 1.0
     
    xb[0] = xb[0] + Jb
    xb[1] = xb[1] + Jb
    Jb    = 0.0
    
    x = tape.pop()
    xb[0] = xb[0] + xb[1]
    xb[1] = 2*x[1]*xb[1]
    
    x = tape.pop()
    xb[1] = xb[0] + xb[1]
    xb[0] = 2*x[0]*xb[0]
    
    return xb
    
adj_store_grad()

array([4., 4.])